--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)


-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
--Q1.What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS total_revenue
FROM customer_data_cleaned
GROUP BY gender;

--Q2.Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount from customer_data_cleaned where discount_applied ='yes' and purchase_amount >(select avg(purchase_amount)from customer_data_cleaned)

--Q3.Which are the top 5 products with the highest average review rating?
select top 5 item_purchased,round(AVG(review_rating),2 ) as average_rating from customer_data_cleaned group by item_purchased order by average_rating desc;

--Q4.Compare the average Purchase Amounts between Standard and Express Shipping.
select avg(purchase_amount)as average_purchase,shipping_type from customer_data_cleaned where shipping_type in('Express','standard')group by shipping_type;

--Q5.Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select avg(purchase_amount) as average_spend,sum(purchase_amount) as revenue,subscription_status from customer_data_cleaned group by subscription_status;

--Q6.Which 5 products have the highest percentage of purchases with discounts applied?
select top 5 item_purchased, round(100 sum( case when discount_applied = 'yes' Then 1 else 0 end)/count(),2) as discount_rate from customer_data_cleaned group by item_purchased order by discount_rate desc;

--Q7.Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with segment_total as (
select customer_id,
case
when previous_purchases = 1 then 'new'
when previous_purchases between 2 and 10 then 'returning'
else 'loyal'
end as segment_wise_total
from customer_data_cleaned

)
select segment_wise_total,count(customer_id)as each_segment from segment_total
group by segment_wise_total
order by each_segment desc
;

--Q8.What are the top 3 most purchased products within each category?
with rank_data as (
select customer_id,category,
ROW_NUMBER() over(partition by category order by customer_id )as most_purchased
from customer_data_cleaned
group by category,customer_id
)
select customer_id,category,most_purchased
from rank_data
where most_purchased <=3
;

--Q9.Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id)as repeted_buyer
from customer_data_cleaned
where previous_purchases >5
group by subscription_status
;

--Q10.What is the revenue contribution of each age group?
select sum(purchase_amount) as total_revenu,age_group
from customer_data_cleaned
group by age_group
